[package]
name = "zed_roslynrs"
version = "0.1.2"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
path = "src/csharp.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
