id = "roslynls"
name = "C#"
description = "C# support."
version = "0.1.2"
schema_version = 1
authors = [
    "fminkowski <fminkowski@gmail.com>",
    "Fabian Freimueller <fabianfreimueller@gmail.com>",
    "fallenwood <fallenwood.y@outlook.com>",
]
repository = "https://github.com/fallenwood/zed-roslynls"

[language_servers.roslyn]
name = "Roslyn"
language = "CSharp"

[debug_adapters.netcoredbg]

[debug_locators.dotnet]

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "6563c3af3f03ec948d08f9325e4bbd072e4c6b99"
